server:
  port:8080

spring:
  batch:
    jdbc:
      initialize-schema: always
    names: ${job.name:testJob1}
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/scheduler
    username: root
    password: root

logging:
  level:
    root: warn
    org.hibernate.type.descriptor.sql: trace